version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    ports:
      - "8000:8000"
    depends_on:
      - dev-db
    environment:
      - DATABASE_URL=postgresql://postgres-dev-user:password@db:5432/qrafty_dev_db
      - PYTHONUNBUFFERED=1

  dev-db: 
    image: postgres:latest
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres-dev-user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qrafty_dev_db
    ports:
      - "5432:5432"
    expose:
      - "5432"

  test-db: 
    image: postgres:latest
    volumes:
      - postgres_test_data:/var/lib/postgresql/data:cached
    environment:
      - POSTGRES_USER=postgres-test-user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qrafty_test_db
    ports:
      - "5434:5434"
    expose:
      - "5434"

volumes:
  postgres_dev_data:
  postgres_test_data:
