version: '3'
name: qrafty
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev # Use the 'dev" stage when targeting development environments builds
    volumes:
      - .:/workspace:cached
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${ENVIRONMENT}
      - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev # Use the 'dev" stage when targeting development environment builds
    volumes:
      - .:/workspace:cached
    ports:
      - "8000:8000"
    depends_on:
      - dev-db
      - test-db
    environment:
      - DEV_DATABASE_URL=${DEV_DATABASE_URL}
      - TEST_DATABASE_URL=${TEST_DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    command: >
      bash -c "export ENVIRONMENT=testing && \ 
               cd backend && \ configs:
               alembic upgrade head && \ 
               tail -f /dev/null "

  dev-db:
    image: postgres:latest
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_DEV_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DEV_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DEV_DB}
    ports:
      - "5432:5432"
    expose:
      - "5432"

  test-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_TEST_USER}
      - POSTGRES_PASSWORD=${POSTGRES_TEST_PASSWORD}
      - POSTGRES_DB=${POSTGRES_TEST_DB}
    ports:
      - "5433:5432"
    expose:
      - "5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - dev-db
      - test-db

  playwright:
    container_name: playwright-server
    image: mcr.microsoft.com/playwright:v1.48.0-noble
    ports:
      - "9222:9222"
    command: [ "npx", "-y", "playwright@1.48.0", "run-server", "--port", "9222" ]

volumes:
  postgres_dev_data:


