/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * QRafty API
 * QRafty API helps to manage and create QR codes, allowing the user to create, edit and delete fully custom QR codes.
 * OpenAPI spec version: 0.1.0
 */

/**a
 * @summary Register:Register
 */
export type authRegisterResponse = {
  data: UserRead;
  status: number;
};

export const getAuthRegisterUrl = () => {
  return `/auth/register`;
};

// export const authRegisterRegister = (
//   userCreate: UserCreate,
//   // eslint-disable-next-line
//   options?: RequestInit
// ): AsyncData<
//   Promise<authRegisterRegisterResponse> | null,
//   FetchError<HTTPValidationError | ValidationError> | null
// > => {
//   return useAPI<Promise<authRegisterRegisterResponse>>(
//     getAuthRegisterRegisterUrl(),
//     {
//       ...options,
//       method: 'POST',
//       headers: { 'Content-Type': 'application/json' },
//       body: JSON.stringify(userCreate)
//     }
//   );
// };

export const authRegister = (
  userCreate: UserCreate,
  // eslint-disable-next-line
  options?: RequestInit
): Promise<authRegisterResponse> => {
  // Import custom fetch instance for QRafty API
  const { $api } = useNuxtApp();

  return $api<authRegisterResponse>(getAuthRegisterUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(userCreate)
  });
};
